version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt

linters-settings:
  funlen:
    lines: 100
    statements: 50
  gosec:
    excludes:
      - G404 # Use of weak random is intentional for deterministic PoI
      - G115 # Integer overflow conversions are checked
  mnd:
    ignored-functions:
      - 'time.Sleep'
      - 'time.After'
      - 'time.NewTicker'
